export const technologies = {
  JavaScript: 'JavaScript',
  TypeScript: 'TypeScript',
  React: 'React',
  Redux: 'Redux',
  ReduxToolkit: 'ReduxToolkit',
  RTKQuery: 'RTK Query',
  NodeJS: 'Node.js',
  NestJS: 'NestJS',
  Express: 'Express',
  MySQL: 'MySQL',
  TypeORM: 'TypeORM',
  MongoDB: 'MongoDB',
  HTML: 'HTML5',
  CSS: 'CSS3',
  Sass: 'Sass',
  StyledComponents: 'styled-components',
  Tailwind: 'Tailwind',
  Bulma: 'Bulma',
  Passport: 'Passport',
  Nodemailer: 'Nodemailer',
  Stripe: 'Stripe',
  Winston: 'Winston',
};
